// style.js
import { StyleSheet } from "react-native";

const syTop = null;

export default StyleSheet.create({
  sTop: {
    top: syTop,
  },
  navbar: {
    textTransform: "uppercase",
    position: 'absolute',
    left: 0,
    right: 0,
    height: 70,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    backgroundColor: '#4680ff',
    zIndex: 100,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 6,
    elevation: 12,
  },
  logo: {
    color: 'white',
    fontSize: 24,
    fontWeight: '800',
    letterSpacing: 1,
  },
  viewBox: {
    padding: 25,
    top: 100,
  },
  navMenu: {
    backgroundColor: "#fdfdfd",
    position: "absolute",
    zIndex: 101,
    height: "100%",
    width: "80%",
    borderRadius: 25,
    padding: 25,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 15,
  },
  btnT: {
    backgroundColor: '#4680ff',
    marginVertical: 6,
    paddingVertical: 16,
    paddingHorizontal: 22,
    borderRadius: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 10,
  },
  btnText: {
    fontSize: 18,
    fontWeight: "700",
    color: "#fff",
    textAlign: "center",
    letterSpacing: 0.5,
  },
  btnCenter: {
    fontSize: 18,
    textAlign: "center",
    fontWeight: "700",
    color: "#fff",
  },
  bottomSide: {
    bottom: 0,
    padding: 15,
    position: "absolute",
    opacity: 0.7,
    backgroundColor: "#fff",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  iTag: {
    fontStyle: "italic",
    color: "#555",
  },
  textCenter: {
    textAlign: "center",
  },
  bigText: {
    textTransform: "uppercase",
    fontSize: 34,
    color: "#555",
    margin: 5,
    fontWeight: "800",
    letterSpacing: 1,
  },
  cRed: {
    color: "red",
    fontWeight: "700",
  },
  input: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 15,
    padding: 14,
    marginVertical: 10,
    fontSize: 16,
    backgroundColor: "#fff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 5,
  },
  btn: {
    marginVertical: 20,
    borderRadius: 100,
  },
  userBox: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: 20,
    borderWidth: 0.5,
    borderColor: "#e0e0e0",
    marginVertical: 12,
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 7,
  },
  profileImage: {
    width: 70,
    height: 70,
    borderRadius: 50,
    marginRight: 18,
    borderWidth: 2,
    borderColor: "#4680ff",
  },
  userName: {
    fontSize: 22,
    fontWeight: "800",
    color: "#333",
    marginBottom: 6,
  },
  userDetail: {
    fontSize: 16,
    color: "#555",
    marginBottom: 4,
  },
  socialRow: {
    flexDirection: "row",
    marginTop: 10,
  },
  popup: {
    width: "90%",
    backgroundColor: "#fff",
    padding: 25,
    borderRadius: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 15,
  },
  upper: {
    textTransform: "uppercase",
  },
  medel: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  viewBoxi: {
    top: 75,
    paddingHorizontal: 20,
  },
  inputx: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 15,
    textTransform: "uppercase",
    padding: 14,
    backgroundColor: "#fff",
    fontSize: 16,
  },
  sidemanu: {
    backgroundColor: "#fff",
    height: "auto",
    width: 260,
    top: 55,
    right: 0,
    position: "absolute",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#e0e0e0",
    padding: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 7,
  },
  mybtn: {
    width: "100%",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#e0e0e0",
    padding: 18,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
    elevation: 7,
    backgroundColor: "#fff",
    marginVertical: 6,
  },
});